### ISSUE TITLE
 _get_label_or_level_values KeyError: 'GENE'

### ISSUE THREAD

**Issue by JonThom** [perslab/CELLECT#24]
**Command:** 

`snakemake` --use-conda --forceall -s `cellect-ldsc.snakefile`

**Expected behaviour**

output CELLECT results

**Actual behaviour**

```
Loading default config file: config-ldsc.yml

Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        22      10
        22      9
        1       all
        44      compute_LD_scores
        44      compute_LD_scores_all_genes
        2       format_and_map_all_genes
        147     format_and_map_genes
        44      make_annot
        44      make_annot_all_genes
        2       make_cts_file
        2       make_multigenesets
        102     prioritize_annotations
        476
[Fri Sep 27 15:12:03 2019]
rule make_multigenesets:
    input: /projects/jonatan/tools/sc-genetics/timshel-bmicelltypes2019/out/es/moffitt2018.mu.csv.gz
    output: /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/precomputation/multi_genesets/multi_geneset.moffitt2018.txt, /scratch/rkm916/BMIcelltypes/CELLE$
T-LDSC/precomputation/multi_genesets/all_genes.multi_geneset.moffitt2018.txt
    jobid: 475
    wildcards: BASE_OUTPUT_DIR=/scratch/rkm916/BMIcelltypes/CELLECT-LDSC, run_prefix=moffitt2018
Activating conda environment: /nfsdata/projects/jonatan/tools/sc-genetics/CELLECT/.snakemake/conda/3d4bc1fb
[Fri Sep 27 15:12:09 2019]
Finished job 475.
1 of 476 steps (0.21%) done

[Fri Sep 27 15:12:09 2019]
rule format_and_map_genes:
    input: /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/precomputation/multi_genesets/multi_geneset.moffitt2018.txt
    output: /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/precomputation/moffitt2018/bed/moffitt2018.Immature_oligodendrocyte_1.bed
    log: /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/logs/log.format_and_map_snake.moffitt2018.Immature_oligodendrocyte_1.txt
    jobid: 394
    wildcards: BASE_OUTPUT_DIR=/scratch/rkm916/BMIcelltypes/CELLECT-LDSC, run_prefix=moffitt2018, annotation=Immature_oligodendrocyte_1

Activating conda environment: /nfsdata/projects/jonatan/tools/sc-genetics/CELLECT/.snakemake/conda/3d4bc1fb
Traceback (most recent call last):
  File "/nfsdata/projects/jonatan/tools/sc-genetics/CELLECT/.snakemake/scripts/tmp4e4xg1v9.format_and_map_snake.py", line 111, in <module>
    multi_gene_sets_to_dict_of_beds(df_multi_gene_set_human, df_gene_coords, windowsize, bed_out_dir + '/tmp', bed_out_dir, out_prefix)
  File "/nfsdata/projects/jonatan/tools/sc-genetics/CELLECT/.snakemake/scripts/tmp4e4xg1v9.format_and_map_snake.py", line 88, in multi_gene_sets_to_di
ct_of_beds
    df = pd.merge(df_gene_coord, df_group, left_on="GENE", right_on="gene", how = "inner")
  File "/nfsdata/projects/jonatan/tools/sc-genetics/CELLECT/.snakemake/conda/3d4bc1fb/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line
47, in merge
    validate=validate)
  File "/nfsdata/projects/jonatan/tools/sc-genetics/CELLECT/.snakemake/conda/3d4bc1fb/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line
529, in __init__
    self.join_names) = self._get_merge_keys()
  File "/nfsdata/projects/jonatan/tools/sc-genetics/CELLECT/.snakemake/conda/3d4bc1fb/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line
846, in _get_merge_keys
    left_keys.append(left._get_label_or_level_values(lk))
  File "/nfsdata/projects/jonatan/tools/sc-genetics/CELLECT/.snakemake/conda/3d4bc1fb/lib/python3.6/site-packages/pandas/core/generic.py", line 1706,
in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'GENE'

[Fri Sep 27 15:12:14 2019]
Error in rule format_and_map_genes:
    jobid: 394
    output: /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/precomputation/moffitt2018/bed/moffitt2018.Immature_oligodendrocyte_1.bed
    log: /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/logs/log.format_and_map_snake.moffitt2018.Immature_oligodendrocyte_1.txt (check log file(s) for err
or message)
    conda-env: /nfsdata/projects/jonatan/tools/sc-genetics/CELLECT/.snakemake/conda/3d4bc1fb

RuleException:
CalledProcessError in line 422 of /nfsdata/projects/jonatan/tools/sc-genetics/CELLECT/cellect-ldsc.snakefile:
Command 'source /tools/anaconda/latest/bin/activate '/nfsdata/projects/jonatan/tools/sc-genetics/CELLECT/.snakemake/conda/3d4bc1fb'; set -euo pipefail
;  python /nfsdata/projects/jonatan/tools/sc-genetics/CELLECT/.snakemake/scripts/tmp4e4xg1v9.format_and_map_snake.py' returned non-zero exit status 1.
  File "/nfsdata/projects/jonatan/tools/sc-genetics/CELLECT/cellect-ldsc.snakefile", line 422, in __rule_format_and_map_genes
  File "/home/cbmr/rkm916/.conda/envs/rkm916_default/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /nfsdata/projects/jonatan/tools/sc-genetics/CELLECT/.snakemake/log/2019-09-27T145804.226630.snakemake.log
```

**Comment by pascaltimshel** [comment]
Problem seems to be related to this line in `format_and_map_snake.py`:
`df = pd.merge(df_gene_coord, df_group, left_on="GENE", right_on="gene", how = "inner")`

**Comment by pascaltimshel** [comment]
@JonThom : the error is caused by incomplete 'cloning' of the repo.  I think you Git LFS might not be setup correctly. Can you please try again and make sure to follow the instructions here: https://github.com/perslab/CELLECT#installation

Here is what the file in your cloned repo looks like:
```bash
(/tools/anaconda/envs/djw472/py3_PT) timshel@yggdrasil:/nfsdata/projects/jonatan/tools/sc-genetics/CELLECT/data/ldsc> cat gene_annotation.hsapiens_all_genes.GRCh37.ens_v91.LDSC_fmt.txt
version https://git-lfs.github.com/spec/v1
oid sha256:2c9e8262c8c1ed47072260afab9ab9cb873ea25e65e83cfe91a4f3f5181223e5
size 3156092
(/tools/anaconda/envs
```
Here is what it should look like:
https://media.githubusercontent.com/media/perslab/CELLECT/master/data/ldsc/gene_annotation.hsapiens_all_genes.GRCh37.ens_v91.LDSC_fmt.txt
