### ISSUE TITLE
ModuleNotFoundError: No module named 'datrie'

### ISSUE THREAD

**Issue by JonThom** [perslab/CELLECT#27]
Trying to run CELLECT as per instructions, seems the datrie module isn't available. I remember this happening before and overcoming it, don't remember how. Any ideas?

> (base) -bash-4.2$ snakemake --use-conda -s cellect-ldsc.snakefile

> Loading default config file: config-ldsc.yml
> Traceback (most recent call last):
>   File "/tools/anaconda/latest/lib/python3.7/site-packages/snakemake/__init__.py", line 551, in snakemake
>     export_cwl=export_cwl)
>   File "/tools/anaconda/latest/lib/python3.7/site-packages/snakemake/workflow.py", line 415, in execute
>     keep_remote_local=keep_remote_local)
>   File "/tools/anaconda/latest/lib/python3.7/site-packages/snakemake/dag.py", line 117, in __init__
>     self.update_output_index()
>   File "/tools/anaconda/latest/lib/python3.7/site-packages/snakemake/dag.py", line 224, in update_output_index
>     self.output_index = OutputIndex(self.rules)
>   File "/tools/anaconda/latest/lib/python3.7/site-packages/snakemake/output_index.py", line 13, in __init__
>     import datrie
> ModuleNotFoundError: No module named 'datrie'

**Comment by JonThom** [comment]
Solved by reinstalling snakemake

**Comment by Tobi1kenobi** [comment]
Is an issue with installing Snakemake with pip rather than bioconda, if I remember correctly
