### ISSUE TITLE
CELLECT LDSC Tutorial produces numpy import error

### ISSUE THREAD

**Issue by pvtodorov** [perslab/CELLECT#36]
Following the tutorial produces a numpy import error, particularly
```
petar@/raid5/home/cbmr/nmq407/Code/CELLECT$ python ldsc/mtag_munge.py \
> --sumstats example/GWAS_EA_excl23andMe.txt \
> --merge-alleles data/ldsc/w_hm3.snplist \
> --n-value 766345 \
> --out example/EA3_Lee2018
Traceback (most recent call last):
  File "ldsc/mtag_munge.py", line 14, in <module>
    from scipy.stats import chi2
  File "/tools/anaconda/envs/nmq407/ldsc_munge/lib/python2.7/site-packages/scipy/stats/__init__.py", line 367, in <module>
    from .stats import *
  File "/tools/anaconda/envs/nmq407/ldsc_munge/lib/python2.7/site-packages/scipy/stats/stats.py", line 172, in <module>
    import scipy.special as special
  File "/tools/anaconda/envs/nmq407/ldsc_munge/lib/python2.7/site-packages/scipy/special/__init__.py", line 641, in <module>
    from ._ufuncs import *
  File "_ufuncs.pyx", line 1, in init scipy.special._ufuncs
  File "_ufuncs_extra_code_common.pxi", line 34, in init scipy.special._ufuncs_cxx
  File "__init__.pxd", line 1038, in numpy.import_array
ImportError: numpy.core.multiarray failed to import
```
I've tried with numpy=1.11.3 which should also work according to the environment yaml, but produce the same result. The bug where the script hangs for a long time with numpy 1.6.4 is also reproduced.

Full trace below
```
-------------------------------------------------------------------------------------------------- 16:00:48
petar@/raid5/home/cbmr/nmq407/Code/CELLECT$ conda env create -f ldsc/environment_munge.yml
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.7.12
  latest version: 4.8.1

Please update conda by running

    $ conda update -n base -c defaults conda


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Ran pip subprocess with arguments:
['/tools/anaconda/envs/nmq407/ldsc_munge/bin/python', '-m', 'pip', 'install', '-U', '-r', '/raid5/home/cbmr/nmq407/Code/CELLECT/ldsc/condaenv.2u9_2h4v.requirements.txt']
Pip subprocess output:
Collecting pandas==0.20.1
  Using cached https://files.pythonhosted.org/packages/9c/58/6d1c670a9040c1862b9a6b65e3f97743ceef8afccba716b2f8d962d7fc94/pandas-0.20.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting numpy==1.13.1
  Using cached https://files.pythonhosted.org/packages/5f/d2/9fa0201944933afd6d059f1e32aa6bdb203b23ab62fc823d3adf36295b9a/numpy-1.13.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pytz>=2011k
  Using cached https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl
Collecting python-dateutil
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting six>=1.5
  Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Installing collected packages: pytz, numpy, six, python-dateutil, pandas
  Found existing installation: numpy 1.16.5
    Uninstalling numpy-1.16.5:
      Successfully uninstalled numpy-1.16.5
Successfully installed numpy-1.13.1 pandas-0.20.1 python-dateutil-2.8.1 pytz-2019.3 six-1.13.0

#
# To activate this environment, use
#
#     $ conda activate ldsc_munge
#
# To deactivate an active environment, use
#
#     $ conda deactivate

-------------------------------------------------------------------------------------------------- 16:02:19
petar@/raid5/home/cbmr/nmq407/Code/CELLECT$ conda activate ldsc_munge
(/tools/anaconda/envs/nmq407/ldsc_munge) -------------------------------------------------------------------------------------------------- 16:02:28
petar@/raid5/home/cbmr/nmq407/Code/CELLECT$ python ldsc/mtag_munge.py \
> --sumstats example/GWAS_EA_excl23andMe.txt \
> --merge-alleles data/ldsc/w_hm3.snplist \
> --n-value 766345 \
> --out example/EA3_Lee2018
Traceback (most recent call last):
  File "ldsc/mtag_munge.py", line 14, in <module>
    from scipy.stats import chi2
  File "/tools/anaconda/envs/nmq407/ldsc_munge/lib/python2.7/site-packages/scipy/stats/__init__.py", line 367, in <module>
    from .stats import *
  File "/tools/anaconda/envs/nmq407/ldsc_munge/lib/python2.7/site-packages/scipy/stats/stats.py", line 172, in <module>
    import scipy.special as special
  File "/tools/anaconda/envs/nmq407/ldsc_munge/lib/python2.7/site-packages/scipy/special/__init__.py", line 641, in <module>
    from ._ufuncs import *
  File "_ufuncs.pyx", line 1, in init scipy.special._ufuncs
  File "_ufuncs_extra_code_common.pxi", line 34, in init scipy.special._ufuncs_cxx
  File "__init__.pxd", line 1038, in numpy.import_array
ImportError: numpy.core.multiarray failed to import
(/tools/anaconda/envs/nmq407/ldsc_munge) -------------------------------------------------------------------------------------------------- 16:02:40
petar@/raid5/home/cbmr/nmq407/Code/CELLECT$ conda list
# packages in environment at /tools/anaconda/envs/nmq407/ldsc_munge:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
argparse                  1.4.0                    py27_0    bioconda
bitarray                  0.8.3           py27h14c3975_1000    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py27_0    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_1    conda-forge
libgfortran-ng            7.3.0                hdf63c60_3    conda-forge
libgomp                   9.2.0                h24d8f2e_1    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
nose                      1.3.7                 py27_1003    conda-forge
numpy                     1.13.1                   pypi_0    pypi
openmp_impl               4.5                       0_gnu    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
pandas                    0.20.1                   pypi_0    pypi
pip                       19.3.1                   py27_0    conda-forge
python                    2.7.15            h5a48372_1009    conda-forge
python-dateutil           2.8.1                    pypi_0    pypi
pytz                      2019.3                   pypi_0    pypi
readline                  8.0                  hf8c457e_0    conda-forge
scipy                     1.2.1            py27h921218d_2    conda-forge
setuptools                44.0.0                   py27_0    conda-forge
six                       1.13.0                   pypi_0    pypi
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
wheel                     0.33.6                   py27_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
(/tools/anaconda/envs/nmq407/ldsc_munge) -------------------------------------------------------------------------------------------------- 16:03:02
petar@/raid5/home/cbmr/nmq407/Code/CELLECT$ python --version
Python 2.7.15
(/tools/anaconda/envs/nmq407/ldsc_munge) -------------------------------------------------------------------------------------------------- 16:03:08
```

**Comment by pvtodorov** [comment]
while `environment_munge.yml` produces numpy import error, using `environment.yml` gives an environment that successfully munges the data.

**Comment by pascaltimshel** [comment]
Thanks @pvtodorov for your help on making CELLECT pain-free for the next users.
As I recall it, the `ldsc_munge` env (`environment_munge.yml`) was only intended for `munge_sumstats.py` - not `mtag_munge.py`. The documentation is just not clear on this at all.

Can you verify that `ldsc_munge` works with `munge_sumstats.py`?

**Comment by pascaltimshel** [comment]
Looks like our channels have different orders of priority (I don't use conda-forge).
Our numpy, scipy and pandas versions are the same, but there are other differences.

My `ldsc_munge` env from a fresh installation:
```conda list
# packages in environment at /tools/anaconda/envs/djw472/ldsc_munge:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
argparse                  1.4.0                    py27_0    bioconda
bitarray                  0.8.3            py27h14c3975_0
blas                      1.0                         mkl
ca-certificates           2019.5.15                     1
certifi                   2019.6.16                py27_1
intel-openmp              2019.4                      243
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libstdcxx-ng              9.1.0                hdf63c60_0
mkl                       2019.4                      243
mkl-service               2.0.2            py27h7b6447c_0
mkl_fft                   1.0.14           py27ha843d7b_0
mkl_random                1.0.2            py27hd81dba3_0
ncurses                   6.1                  he6710b0_1
nose                      1.3.7                    py27_2
numpy                     1.13.1                   pypi_0    pypi
openssl                   1.1.1c               h7b6447c_1
pandas                    0.20.1                   pypi_0    pypi
pip                       19.2.2                   py27_0
python                    2.7.16               h8b3fad2_4
python-dateutil           2.8.0                    pypi_0    pypi
pytz                      2019.2                   pypi_0    pypi
readline                  7.0                  h7b6447c_5
scipy                     1.2.1            py27h7c811a0_0
setuptools                41.0.1                   py27_0
six                       1.12.0                   py27_0
sqlite                    3.29.0               h7b6447c_0
tk                        8.6.8                hbc83047_0
wheel                     0.33.4                   py27_0
zlib                      1.2.11               h7b6447c_3
```

**Comment by pascaltimshel** [comment]
Fixed in update of ldsc submodule: https://github.com/perslab/CELLECT/commit/e49e1a4513af4cd08972ca323f2ca36ff7e41cf9
