### ISSUE TITLE
Error in rule parse_results

### ISSUE THREAD

**Issue by vgastaldi** [perslab/CELLECT#39]
**Issue**

I cannot run CELLECT using anything but Ensembl Gene. I am not sure if this is by design, but as CELLEX gives other options (including in the tutorial) I did not believe it would be an issue.

```
INFO:parse_results:Compiling prioritization result files from 1 files
Traceback (most recent call last):
  File "/home/vdaguano/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2890, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/parse_results.py", line 116, in <module>
    main(args.base_output_dir, logger)
  File "scripts/parse_results.py", line 39, in main
    prioritization_combined['specificity_id'] = specificity_id_annotation[0] #mousebrain
  File "/home/vdaguano/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 2975, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/vdaguano/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2892, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0
[Fri Feb 14 12:26:33 2020]
Error in rule parse_results:
    jobid: 1
    output: /home/vdaguano/CELLECT/run1/results/prioritization.csv
    shell:
        python3 scripts/parse_results.py --base_output_dir /home/vdaguano/CELLECT/run1
```

**Comment by Tobi1kenobi** [comment]
Hi Vinicius,

Indeed at the moment CELLECT only supports genes in Ensembl human format as mentioned in the [https://github.com/perslab/CELLECT/wiki/CELLECT-LDSC-Docs#specificity_input](wiki). CELLEX can return other formats but this functionality is intended for alternate downstream uses for expression specificity, not for CELLECT.

All the best,
Tobi

**Comment by vgastaldi** [comment]
Hi Tobi,

Thank you for the reply.

Sorry for opening this issue, I completely missed this part of the documentation.

Best,

Vinicius
