### ISSUE TITLE
error when run cellect-ldsc.snakefile

### ISSUE THREAD

**Issue by frucelee** [perslab/CELLECT#90]
Hi, 

Thanks a lot for the nice software.

When I run the fowtare using the exmple data: snakemake --use-conda -s cellect-ldsc.snakefile --configfile config.yml  

A error was shown below:

 /scratch/users/f/l/lee/ldsc/CELLECT/cellect-ldsc.snakefile:44: SyntaxWarning: invalid escape sequence '\d'
  gwas = r"|".join(set(GWAS_SUMSTATS.keys()))
/scratch/users/f/l/lee/ldsc/CELLECT/cellect-ldsc.snakefile:445: SyntaxWarning: invalid escape sequence '\d'
  output:
/scratch/users/f/l/lee/ldsc/CELLECT/cellect-ldsc.snakefile:500: SyntaxWarning: invalid escape sequence '\d'
Traceback (most recent call last):
  File "/home/ucm/immvac/lee/miniconda3/envs/cellect/lib/python3.12/site-packages/snakemake/cli.py", line 1886, in args_to_api
    dag_api = workflow_api.dag(
              ^^^^^^^^^^^^^^^^^
  File "/home/ucm/immvac/lee/miniconda3/envs/cellect/lib/python3.12/site-packages/snakemake/api.py", line 326, in dag
    return DAGApi(
           ^^^^^^^
  File "<string>", line 6, in __init__
  File "/home/ucm/immvac/lee/miniconda3/envs/cellect/lib/python3.12/site-packages/snakemake/api.py", line 436, in __post_init__
    self.workflow_api._workflow.dag_settings = self.dag_settings
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ucm/immvac/lee/miniconda3/envs/cellect/lib/python3.12/site-packages/snakemake/api.py", line 383, in _workflow
    workflow.include(
  File "/home/ucm/immvac/lee/miniconda3/envs/cellect/lib/python3.12/site-packages/snakemake/workflow.py", line 1374, in include
    exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)
  File "/scratch/users/f/l/lee/ldsc/CELLECT/cellect-ldsc.snakefile", line 3, in <module>
    include: "rules/common_func1.smk"
  File "/home/ucm/immvac/lee/miniconda3/envs/cellect/lib/python3.12/site-packages/snakemake/workflow.py", line 1374, in include
    exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)
  File "/scratch/users/f/l/lee/ldsc/CELLECT/rules/common_func1.smk", line 122, in <module>
AttributeError: module 'snakemake' has no attribute 'logger'

Do you know what happened and how can I fix them? I try different solutions, but no success. Thanks a lot.

Best,

Lee

**Comment by wzy548582** [comment]
hello, have you solved this problem? I also encountered this problem. Could you please tell me the solution.

**Comment by kirito002** [comment]
same problem I encountered.
