### ISSUE TITLE
rule compute LD scores: numpy issue when running on a singularity image

### ISSUE THREAD

**Issue by ElizabethWallace97** [perslab/CELLECT#95]
I am running CELLECT on a singularity image by necessity (large files that need to be run on a remote data cluster). I am running into this error when the ldsc reaches the compute_LD_scores step and cannot figure out how to solve it: 
`Error in rule compute_LD_scores_all_genes:
    jobid: 128
    input: /data/CELLECT_ATAC/CELLECT-LDSC/precomputation/control.all_genes_in_dataset/all_genes_in_data.18.annot.gz
    output: /project/stefanoberto/musc/ASD_Multiome/CELLECT_ATAC/CELLECT-LDSC/precomputation/control.all_genes_in_dataset/all_genes_in_data.18.l2.ldscore.gz, /data/CELLECT_ATAC/CELLECT-LDSC/precomputation/control.all_genes_in_dataset/all_genes_in_data.18.l2.M, /data/CELLECT_ATAC/CELLECT-LDSC/precomputation/control.all_genes_in_dataset/all_genes_in_data.18.l2.M_5_50, /data/CELLECT_ATAC/CELLECT-LDSC/precomputation/control.all_genes_in_dataset/all_genes_in_data.18.log
    log: /data/CELLECT_ATAC/CELLECT-LDSC/logs/log.compute_LD_scores.all_genes_in_dataset.data.18.txt (check log file(s) for error details)
    conda-env: /home/elizabethwallace/f9098b7cb53074bc8a6e22639fba8910_
    shell:
        /home/elizabethwallace/Documents/CELLECT/ldsc/ldsc.py --l2 --bfile /home/elizabethwallace/Documents/CELLECT/data/ldsc/1000G_EUR_Phase3_plink/1000G.EUR.QC.18 --ld-wind-cm 1 		--annot /data/CELLECT_ATAC/CELLECT-LDSC/precomputation/control.all_genes_in_dataset/all_genes_in_ASD_Multiome.18.annot.gz 		--thin-annot --out /data/CELLECT_ATAC/CELLECT-LDSC/precomputation/control.all_genes_in_dataset/all_genes_in_data.18 		 --print-snps /home/elizabethwallace/Documents/CELLECT/data/ldsc/print_snps.txt &> /data/CELLECT_ATAC/CELLECT-LDSC/logs/log.compute_LD_scores.all_genes_in_dataset.data.18.txt
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
`

Log file: 
`Traceback (most recent call last):
  File "/home/elizabethwallace/Documents/CELLECT/ldsc/ldsc.py", line 12, in <module>
    import ldscore.ldscore as ld
  File "/home/elizabethwallace/Documents/CELLECT/ldsc/ldscore/ldscore.py", line 2, in <module>
    import numpy as np
  File "/home/elizabethwallace/f9098b7cb53074bc8a6e22639fba8910_/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/home/elizabethwallace/f9098b7cb53074bc8a6e22639fba8910_/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/elizabethwallace/f9098b7cb53074bc8a6e22639fba8910_/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/elizabethwallace/f9098b7cb53074bc8a6e22639fba8910_/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/elizabethwallace/f9098b7cb53074bc8a6e22639fba8910_/lib/python2.7/site-packages/numpy/core/__init__.py", line 24, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.`

The singularity def file is as follows:
`Bootstrap: docker
From: continuumio/miniconda3:latest

%post
	apt-get update && apt-get install -y nano wget git build-essential git-lfs libz-dev
	git clone --recurse-submodules https://github.com/perslab/CELLECT.git
	conda install python=3.8
	conda install -c bioconda -c conda-forge snakemake mamba 
	pip install pybedtools numpy==1.16 pandas`

**Comment by HansLambda** [comment]
I think I had this issue once, it's caused by the numpy package in the conda environment that is set up to run python2.7. The error message should point you to the offending conda env `conda-env: /home/elizabethwallace/f9098b7cb53074bc8a6e22639fba8910_` 
If you manually activate this environment and run `python`, try `>>>import numpy`. If that gives the same error `ImportError:  Importing the multiarray numpy extension module failed.` then exit python and reinstall numpy in this specific conda environment.
